extends:
- airbnb-base

plugins:
- '@typescript-eslint'

parser: '@typescript-eslint/parser'

env:
  browser: true

rules:
  "no-shadow": "off"
  "@typescript-eslint/no-shadow": "error"
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": "error"
  import/no-unresolved: off
  import/extensions: off
  import/prefer-default-export: off
  max-len: [error, 120]
